Repository vermist-sector/vermist-dust, pull requests merged in 2025-05, with the labels that each got.

#21 Readme Update
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: S: Untriaged, size/S

#23 synthetic trait from deltav & cosmaticdrift
  Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
  Content.Server/StationEvents/Events/IonStormRule.cs
  Content.Server/_CD/Traits/SynthComponent.cs
  Content.Server/_CD/Traits/SynthSystem.cs
  Content.Shared/Chat/TypingIndicator/TypingIndicatorComponent.cs
  Content.Shared/Traits/TraitPrototype.cs
  Resources/Locale/en-US/_CD/reagents/meta/biological.ftl
  Resources/Locale/en-US/_CD/station/events.ftl
  Resources/Locale/en-US/_CD/traits/traits.ftl
  Resources/Prototypes/_CD/Reagents/biological.yml
  Resources/Prototypes/_CD/Traits/traits.yml
Labels: S: Untriaged, size/M

#24 dust sector centcomm
  Content.Server/Shuttles/Components/StationCentcommComponent.cs
  Resources/Maps/_VDS/vds_centcomm.yml
  Resources/Prototypes/Maps/centcomm.yml
Labels: S: Untriaged, size/XL
